# Generated by Django 2.2 on 2021-11-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readmore',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
